module.exports = [
  'IBL_MAIN_RED', 'IBL_MAIN_WHITE', 'IBL_MAIN_BLUE', 'IBL_CWS', 'IBL_CWR', 'IBL_TEMP',
  'IBL_CH1_EFTIN', 'IBL_CH1_EFTOUT', 'IBL_CH1_EFSET', 'IBL_CH2_EFTIN', 'IBL_CH2_EFTOUT', 'IBL_CH2_EFSET',
  'IBL_MAIN_KVA',
];